{% set name = "apache-airflow-providers-ssh" %}
{% set version = "2.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-ssh-{{ version }}.tar.gz
  sha256: 02a4f61be6a95fda402181848dd375907c43f299ab5fe92b93399e838a080500

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - paramiko >=2.6.0
    - pysftp >=0.2.9
    - sshtunnel >=0.3.2

test:
  imports:
    - airflow.providers.ssh
    - airflow.providers.ssh.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Secure Shell (SSH) for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-ssh/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
