{% set name = "apache-airflow-providers-ssh" %}
{% set version = "4.1.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_ssh-{{ version }}.tar.gz
  sha256: 05c5714fa346cead695b559ba5cb30ef4667e6f5d666d68778be969d1aee0366

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - paramiko >=2.9.0,<4.0.0
    - sshtunnel >=0.3.2

test:
  imports:
    - airflow.providers.ssh
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-ssh for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/ssh/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-ssh/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
